# Generated by Django 4.2 on 2024-05-21 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrocontabilidad',
            old_name='Valor',
            new_name='valor',
        ),
    ]
